### ISSUE TITLE
Possibility of removing the prettier parser arguments, or add the ability to configure your own

### ISSUE THREAD

**Issue by venikx** [lassik/emacs-format-all-the-code#175]
Hi,

I'm wondering why the prettier formatter depends on the parser arguments, see: https://github.com/lassik/emacs-format-all-the-code/blob/6200b91d9151b3177a676d30edd948266292bcc1/format-all.el#L1009. Is there some special cases I'm currently unaware of?

According to the prettier documentation, choosing the correct parser is supposed to be handled by prettier itself. If you really need to change some parser, there's possibility to override using the `.prettierrc`, for example:
```json
{
  "overrides": [
    {
      "files": ["*.json"],
      "options": {
        "parser": "json"
      }
    }
  ]
}
```

I'm currently running into an issue with prettier formatting the package.json using the `json5` parser, while Emacs formats it with the `json` parser.

**Comment by lassik** [comment]
Commit 6bcd9a5 should fix JSON5 for prettier. Should be in MELPA in a couple hours. Does it work?

**Comment by lassik** [comment]
JSON5 is detected when you use `json-mode` and the filename extension is `.json5`.

[Code here](https://github.com/lassik/emacs-language-id/blob/c945568a2e40e8d7e9738a534ce54e9ff59779c6/language-id.el#L49)

**Comment by lassik** [comment]
If there are other JSON5 modes for Emacs (e.g. in web-mode), please let me know and I'll add them.

**Comment by venikx** [comment]
The main issue is that prettier by default formats `.json` as `json5`, unless you change that in the parser options I mentioned above. Currently, the workaround is to add the snippet above in your `.prettierrc` so it reflects how `format-all` overrides the parser on the command line, see: https://github.com/lassik/emacs-format-all-the-code/blob/6200b91d9151b3177a676d30edd948266292bcc1/format-all.el#L1009.

Ideally, this line should not be needed as you can configure the parser options with prettier itself, but it does mean if people haven't properly configured prettier parser options in the `.prettierrc` their formatting would suddenly be different.

**Comment by lassik** [comment]
Does prettier use `json5` as the default parser for both `.json` and `.json5` files?

**Comment by venikx** [comment]
From what I tested it seems to be yes, but I think that's beside my point. We shouldn't be overriding the parser options to begin with as you configure the parser options using the `.prettierrc` file.

**Comment by venikx** [comment]
From where I'm looking at, this seems to be a good middle ground. People without a prettier file will still get options defined by format-all, and thus formatting "for free (if they at least have prettier installed) and all the options that are defined in the prettier file override the ones that were defined by format-all.

But again, I'm biased towards using prettierrc files hehe.

**Comment by lassik** [comment]
Please try out the fix I just pushed to the [`lassik-prettier`](https://github.com/lassik/emacs-format-all-the-code/tree/lassik-prettier/) branch.

**Comment by venikx** [comment]
> ```json
> "overrides": [
>     {
>       "files": ["*.json"],
>       "options": {
>         "parser": "json"
>       }
>     }
>   ]
> ```

My apologies for the extreme late reply. I finally got around to testing your branch. Looks like it's working fine! :)
I'll close my PR as well, as it's deprecated by your suggestion.

**Comment by venikx** [comment]
> Please try out the fix I just pushed to the [`lassik-prettier`](https://github.com/lassik/emacs-format-all-the-code/tree/lassik-prettier/) branch.

My apologies for the extreme late reply. I finally got around to testing your branch. Looks like it's working fine! :)
I'll close my PR as well, as it's deprecated by your suggestion.

**Comment by lassik** [comment]
No problem. Glad to hear it works. I merged it to master. Let me know if any problems come up.

For reference, that's commit 828280e.

**Comment by liuyinz** [comment]
@lassik still problem here.
I have file ".yamllint", it's major-mode is `yaml-mode`, but still get no parser error.
